In [1]:
# Importing all necessary libraries

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Read the Excel file

In [2]:
courses = pd.read_excel('course_recommendation.xlsx')

In [3]:
courses.head()

,courseid,title,technology,topic,abstract,url,image_url
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,NaN,https://www.datacamp.com/courses/categorical-d...,NaN
1,2,GARCH Models in R,R,Applied Finance,NaN,https://www.datacamp.com/courses/garch-models-...,NaN
2,3,Structural Equation Modeling with lavaan in R,R,Probability & Statistics,NaN,https://www.datacamp.com/courses/structural-eq...,NaN
3,4,Analyzing IoT Data in Python,Python,Data Manipulation,NaN,https://www.datacamp.com/courses/analyzing-iot...,NaN
4,5,Introduction to Spark SQL in Python,Python,Data Manipulation,NaN,https://www.datacamp.com/courses/introduction-...,NaN

#### Description of the data
## The file contains 4 features about the course which have been uploaded into our database
* title - Title of the Course
* technology - Technology of the course 
* topic - course topic
* abstract - Short summary of the course
* url - Course url - if applicable

In [4]:
# Fill the missing values with empty string

In [5]:
courses.fillna(" ",inplace=True)

In [6]:
courses.head()

,courseid,title,technology,topic,abstract,url,image_url
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,
1,2,GARCH Models in R,R,Applied Finance,,https://www.datacamp.com/courses/garch-models-...,
2,3,Structural Equation Modeling with lavaan in R,R,Probability & Statistics,,https://www.datacamp.com/courses/structural-eq...,
3,4,Analyzing IoT Data in Python,Python,Data Manipulation,,https://www.datacamp.com/courses/analyzing-iot...,
4,5,Introduction to Spark SQL in Python,Python,Data Manipulation,,https://www.datacamp.com/courses/introduction-...,

In [7]:
ratings=pd.read_excel("rating.xlsx")
ratings['rating'] = ratings['rating'].round(1)
ratings.head()

   userid  courseid  rating
0       1       301     4.5
1       2       301     4.7
2       2       423     3.5
3       2        65     4.5
4       3       175     4.4

In [8]:
ratings['userid'].value_counts().shape

(1822,)

In [9]:
# Filterig users who have rated more than 3 courses
x=ratings['userid'].value_counts() >3
x[x].shape

(455,)

In [10]:
# Getting indices of users who have rated more than 3 courses
y=x[x].index


# Filterig rating dataframe for users who have rated more than 3 courses

ratings=ratings[ratings['userid'].isin(y)]
ratings.head()

    userid  courseid  rating
5        4       406     3.3
6        4       302     4.4
7        4       289     4.2
8        4       267     3.3
17      10       275     4.9

In [11]:
# Merging ratings and coursees dataframe on userid

courses_with_rating = courses.merge(ratings,on='courseid')
courses_with_rating.head()

,courseid,title,technology,topic,abstract,url,image_url,userid,rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.5
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.2
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.1
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.8

In [12]:
courses_with_rating.shape

(2169, 9)

In [13]:
number_rating = courses_with_rating.groupby('title')['rating'].count().reset_index()
number_rating

                                                 title  rating
0            3-Axis Machining with Autodesk Fusion 360       7
1                            3D Art and Audio Pipeline       5
2                       A Crash Course in Data Science       6
3                                     A/B Testing in R       5
4                                     ACT Prepaaration       7
..                                                 ...     ...
419                                 pandas Foundations       5
420                              railway jobs in india      14
421  what is post of junior scale officer of goa ci...       4
422  what is rajasthan state and subordinate servic...       5
423  what is uttar pradesh public service commissio...       5

[424 rows x 2 columns]

In [14]:
number_rating.rename(columns={'rating':'number_rating'},inplace=True)
number_rating.head()

                                       title  number_rating
0  3-Axis Machining with Autodesk Fusion 360              7
1                  3D Art and Audio Pipeline              5
2             A Crash Course in Data Science              6
3                           A/B Testing in R              5
4                           ACT Prepaaration              7

In [15]:
courses_with_rating.head()

,courseid,title,technology,topic,abstract,url,image_url,userid,rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.5
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.2
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.1
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.8

In [16]:
# Merging num_rating with courses_with_rating on title 

courses_with_rating = courses_with_rating.merge(number_rating,on='title')
courses_with_rating.head()

,courseid,title,technology,topic,abstract,url,image_url,userid,rating,number_rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.5,6
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.2,6
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.1,6
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.6,6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.8,6

In [17]:
courses_with_rating.shape

(2169, 10)

In [18]:
# Creatign a final dataframe with rating > 3

final_rating = courses_with_rating[courses_with_rating['rating']>=2]

print(final_rating.shape)
final_rating.head()

(2169, 10)

,courseid,title,technology,topic,abstract,url,image_url,userid,rating,number_rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.5,6
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.2,6
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.1,6
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.6,6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.8,6

In [19]:
final_rating.drop_duplicates(['userid','title'],inplace=True)
print(final_rating.shape)
final_rating.head()

(2160, 10)

,courseid,title,technology,topic,abstract,url,image_url,userid,rating,number_rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.5,6
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.2,6
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.1,6
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.6,6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.8,6

In [20]:
# creatign a pivot table to find 
courses_pivot = final_rating.pivot(index='userid',columns='title',values='rating')
courses_pivot.head()

title,3-Axis Machining with Autodesk Fusion 360,3D Art and Audio Pipeline,A Crash Course in Data Science,A/B Testing in R,ACT Prepaaration,API Development on Google Cloud's Apigee API Platform,ARIMA Modeling with R,"Abstraction, Problem Decomposition, and Functions",Actuarial Mathematics (also for non actuaries) Updated!,Adobe Illustrator: How to Draw Squared Animals Icons,...,"how to tackle cat - athira asokan, iim ahmedabad",how to tackle central teacher eligibility test - ctet,how to tackle gate by arvind devaraj - air 7 [i.i.sc. bangalore],how to tackle gre,"how to tackle ielts - rishabh varma, ielts (a - 7.5, g - 8.0)",pandas Foundations,railway jobs in india,what is post of junior scale officer of goa civil service,what is rajasthan state and subordinate services combined competitive examination,what is uttar pradesh public service commission combined state / upper subordinate services examination
userid,,,,,,,,,,,,,,,,,,,,,
4,NaN,NaN,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
courses_pivot.fillna(0,inplace=True)
courses_pivot.head()

title,3-Axis Machining with Autodesk Fusion 360,3D Art and Audio Pipeline,A Crash Course in Data Science,A/B Testing in R,ACT Prepaaration,API Development on Google Cloud's Apigee API Platform,ARIMA Modeling with R,"Abstraction, Problem Decomposition, and Functions",Actuarial Mathematics (also for non actuaries) Updated!,Adobe Illustrator: How to Draw Squared Animals Icons,...,"how to tackle cat - athira asokan, iim ahmedabad",how to tackle central teacher eligibility test - ctet,how to tackle gate by arvind devaraj - air 7 [i.i.sc. bangalore],how to tackle gre,"how to tackle ielts - rishabh varma, ielts (a - 7.5, g - 8.0)",pandas Foundations,railway jobs in india,what is post of junior scale officer of goa civil service,what is rajasthan state and subordinate services combined competitive examination,what is uttar pradesh public service commission combined state / upper subordinate services examination
userid,,,,,,,,,,,,,,,,,,,,,
4,0.0,0.0,4.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
# Input a course name to recommend
#course_name = input("Enter the course name for recommendation")

In [42]:

def recommend_course(course_name):
    user_ratings_for_course = courses_pivot[course_name]
    similar_course = courses_pivot.corrwith(user_ratings_for_course)
    corr_course_name = pd.DataFrame(similar_course,columns=['Correlation'])
    corr_course_name.dropna(inplace=True)
    courses_recommended = corr_course_name.sort_values('Correlation',ascending=False).head(5)
    print(courses_recommended)

In [43]:
recommend_course('3-Axis Machining with Autodesk Fusion 360')

                                               Correlation
title
3-Axis Machining with Autodesk Fusion 360         1.000000
Biomedical Image Analysis in Python               0.336922
Machine Learning for Marketing Analytics in R     0.302070
Software Defined Networking                       0.244464
Analyzing US Census Data in Python                0.223198

In [305]:
recommend_course('ACT Prepaaration')

                                                    Correlation
title
ACT Prepaaration                                       1.000000
IT Fundamentals for Cybersecurity                      0.384337
Course Creation at DataCamp                            0.287474
Foundations of Predictive Analytics in Python (...     0.225551
Interactive Maps with leaflet in R                     0.222200

In [306]:
recommend_course('ACT Prepaaration')

                                                    Correlation
title
ACT Prepaaration                                       1.000000
IT Fundamentals for Cybersecurity                      0.384337
Course Creation at DataCamp                            0.287474
Foundations of Predictive Analytics in Python (...     0.225551
Interactive Maps with leaflet in R                     0.222200

In [307]:
recommend_course("Introduction to Spark SQL in Python")

                                                    Correlation
title
Introduction to Spark SQL in Python                    1.000000
GMAT/SAT/CAT-Permutations, Combinations & Proba...     0.310378
Fraud Detection in Python                              0.244592
Financial Analytics in R                               0.216378
ARIMA Modeling with R                                  0.203944

In [308]:
recommend_course("Categorical Data in the Tidyverse")

                                       Correlation
title
Categorical Data in the Tidyverse         1.000000
Supply Chain Analytics in Python          0.274828
Financial Analytics in Spreadsheets       0.262200
Object-Oriented Programming in Python     0.249950
TOEFL preparation                         0.214277

In [309]:
recommend_course("how to tackle gre")

                                                    Correlation
title
how to tackle gre                                      1.000000
how to tackle central teacher eligibility test ...     0.318912
Network Analysis in R                                  0.308649
Cleaning Data in Python                                0.300594
Vocabulary for SAT, GMAT, GRE, CAT applicants          0.256016

# Conclusion:
    
## Correlation method has recommended the  courses based on similar users rating